### ISSUE TITLE
Module not found: Can't resolve '@nteract/mathjax

### ISSUE THREAD

**Issue by saulpalv** [nteract/markdown#6]
just installed @nteract/markdown

now project won't compile it says

```
./node_modules/@nteract/markdown/lib/markdown-render.js
Module not found: Can't resolve '@nteract/mathjax' in '...path\node_modules\@nteract\markdown\lib'
```

**UPDATE!!**
As commented here : https://github.com/nteract/mathjax/issues/4 mathjax does exits in \node_modules\@nteract\mathjax but it wasn't built so it was missing the `mathjax\lib` folder also its dependency presentational-components has missing the `presentational-components\lib`

i provide a zip with built lib folder, just copy the corresponding libs folder to your node_modules\@nteract\{component missing lib}

You can compile with npm run bild, just verify that pakages,json has   
```
"scripts": {
    "build": "tsc -b",
    "test": "jest"
  },
```
and that tsconfig.json is like this
```
{
  "compilerOptions": {
    "strict": true,
    "declaration": true,
    "esModuleInterop": true,
    "composite": true,
    "lib": ["esnext", "dom"],
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "noImplicitAny": true,
    "outDir": "lib",
    "rootDir": "src",
    "resolveJsonModule": true,
    "preserveWatchOutput": true,
    "jsx": "react",
    "typeRoots": ["./node_modules/@types", "types"]
  },
  "include": ["src"],
  "references": []
}
```

[@nteract.zip](https://github.com/nteract/markdown/files/4741223/%40nteract.zip)

**Comment by ramantehlan** [comment]
Thank you @saulpalv for raising this.

captainsafia pointed out to me that this might be because the prebuild step failed while publishing the `@nteract/mathjax` and `@nteract/presentational-components` package. So, we will have to publish them again to be able to fix it.

An alternative workaround for this can be: 
```
yarn add @nteract/mathjax@4.0.7
yarn add @nteract/presentational-components@3.3.4
yarn add styled-components
```

Same with other package managers and you can reinstall the `node_modules` once the packages are updated.

**Comment by stormpython** [comment]
Is this issue still open or should it be closed?

**Comment by ramantehlan** [comment]
This is fixed now and can be closed. :+1:

**Comment by rgbkrk** [comment]
Thank you @ramantehlan
